//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVosSouhaits
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composant
    {
        public long IdComposant { get; set; }
        public string UrlPhoto { get; set; }
        public string Nom { get; set; }
        public string Note { get; set; }
        public byte[] Image { get; set; }
    }
}
