//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVosSouhaits
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projets
    {
        public long IdProjet { get; set; }
        public Nullable<long> Civilite1 { get; set; }
        public string Nom1 { get; set; }
        public string Prenom1 { get; set; }
        public Nullable<long> Civilite2 { get; set; }
        public string Nom2 { get; set; }
        public string Prenom2 { get; set; }
    }
}
