//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVosSouhaits
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projets
    {
        public long IdProjet { get; set; }
        public Nullable<long> Civilite1 { get; set; }
        public string Nom1 { get; set; }
        public string Prenom1 { get; set; }
        public Nullable<long> Civilite2 { get; set; }
        public string Nom2 { get; set; }
        public string Prenom2 { get; set; }
        public string Adresse { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<long> Budget { get; set; }
        public Nullable<System.DateTime> DateDuMariage { get; set; }
    }
}
